# Generated by Django 3.2.4 on 2021-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetCheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='output',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Вывод программы'),
        ),
        migrations.AlterField(
            model_name='format',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Код формата'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='file',
            field=models.FileField(max_length=1000, upload_to='sheets', verbose_name='Файл ведомости'),
        ),
    ]
