# Generated by Django 3.2.4 on 2021-06-02 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheetCheck', '0002_auto_20210602_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheet',
            old_name='output',
            new_name='response',
        ),
        migrations.AddField(
            model_name='sheet',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
